var Module = (() => {
  var _scriptName = typeof document != 'undefined' ? document.currentScript?.src : undefined;
  if (typeof __filename != 'undefined') _scriptName = _scriptName || __filename;
  return (
async function(moduleArg = {}) {
  var moduleRtn;

var f=moduleArg,aa,q,ba=new Promise((a,b)=>{aa=a;q=b}),da="object"==typeof window,u="undefined"!=typeof WorkerGlobalScope,ea="object"==typeof process&&"object"==typeof process.versions&&"string"==typeof process.versions.node&&"renderer"!=process.type,fa={...f},v="",w,x;
if(ea){var fs=require("fs");require("path");v=__dirname+"/";x=a=>{a=z(a)?new URL(a):a;return fs.readFileSync(a)};w=async a=>{a=z(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.slice(2)}else if(da||u)u?v=self.location.href:"undefined"!=typeof document&&document.currentScript&&(v=document.currentScript.src),_scriptName&&(v=_scriptName),v.startsWith("blob:")?v="":v=v.slice(0,v.replace(/[?#].*/,"").lastIndexOf("/")+1),u&&(x=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType=
"arraybuffer";b.send(null);return new Uint8Array(b.response)}),w=async a=>{if(z(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);};f.print||console.log.bind(console);var A=f.printErr||console.error.bind(console);
Object.assign(f,fa);fa=null;var B=f.wasmBinary,C,ha=!1,E,F,G,H,I,J,ia,ja,ka,la,z=a=>a.startsWith("file://");function ma(){var a=C.buffer;f.HEAP8=E=new Int8Array(a);f.HEAP16=G=new Int16Array(a);f.HEAPU8=F=new Uint8Array(a);f.HEAPU16=H=new Uint16Array(a);f.HEAP32=I=new Int32Array(a);f.HEAPU32=J=new Uint32Array(a);f.HEAPF32=ia=new Float32Array(a);f.HEAPF64=la=new Float64Array(a);f.HEAP64=ja=new BigInt64Array(a);f.HEAPU64=ka=new BigUint64Array(a)}var M=0,N=null;
function na(a){f.onAbort?.(a);a="Aborted("+a+")";A(a);ha=!0;a=new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");q(a);throw a;}var O;async function oa(a){if(!B)try{var b=await w(a);return new Uint8Array(b)}catch{}if(a==O&&B)a=new Uint8Array(B);else if(x)a=x(a);else throw"both async and sync fetching of the wasm failed";return a}
async function pa(a,b){try{var c=await oa(a);return await WebAssembly.instantiate(c,b)}catch(d){A(`failed to asynchronously prepare wasm: ${d}`),na(d)}}async function qa(a){var b=O;if(!B&&"function"==typeof WebAssembly.instantiateStreaming&&!z(b)&&!ea)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){A(`wasm streaming compile failed: ${d}`),A("falling back to ArrayBuffer instantiation")}return pa(b,a)}
var ra=a=>{for(;0<a.length;)a.shift()(f)},sa=[],ta=[],ua=()=>{var a=f.preRun.shift();ta.unshift(a)};class va{constructor(a){this.D=a-24}}
var wa=0,xa=0,ya,P=a=>{for(var b="";F[a];)b+=ya[F[a++]];return b},Q={},R={},S={},T=f.BindingError=class extends Error{constructor(a){super(a);this.name="BindingError"}},za=a=>{throw new T(a);},Aa=f.InternalError=class extends Error{constructor(a){super(a);this.name="InternalError"}},Ba=(a,b)=>{function c(h){h=b(h);if(h.length!==d.length)throw new Aa("Mismatched type converter count");for(var l=0;l<d.length;++l)U(d[l],h[l])}var d=[];d.forEach(h=>S[h]=a);var e=Array(a.length),g=[],m=0;a.forEach((h,
l)=>{R.hasOwnProperty(h)?e[l]=R[h]:(g.push(h),Q.hasOwnProperty(h)||(Q[h]=[]),Q[h].push(()=>{e[l]=R[h];++m;m===g.length&&c(e)}))});0===g.length&&c(e)};function Ca(a,b,c={}){var d=b.name;if(!a)throw new T(`type "${d}" must have a positive integer typeid pointer`);if(R.hasOwnProperty(a)){if(c.G)return;throw new T(`Cannot register type '${d}' twice`);}R[a]=b;delete S[a];Q.hasOwnProperty(a)&&(b=Q[a],delete Q[a],b.forEach(e=>e()))}function U(a,b,c={}){return Ca(a,b,c)}
var Da=(a,b,c)=>{switch(b){case 1:return c?d=>E[d]:d=>F[d];case 2:return c?d=>G[d>>1]:d=>H[d>>1];case 4:return c?d=>I[d>>2]:d=>J[d>>2];case 8:return c?d=>ja[d>>3]:d=>ka[d>>3];default:throw new TypeError(`invalid integer width (${b}): ${a}`);}},V=[],W=[],Ea=a=>{switch(a){case void 0:return 2;case null:return 4;case !0:return 6;case !1:return 8;default:const b=V.pop()||W.length;W[b]=a;W[b+1]=1;return b}};function Fa(a){return this.fromWireType(J[a>>2])}
var Ga={name:"emscripten::val",fromWireType:a=>{if(!a)throw new T("Cannot use deleted val. handle = "+a);var b=W[a];9<a&&0===--W[a+1]&&(W[a]=void 0,V.push(a));return b},toWireType:(a,b)=>Ea(b),C:8,readValueFromPointer:Fa,B:null},Ha=(a,b)=>{switch(b){case 4:return function(c){return this.fromWireType(ia[c>>2])};case 8:return function(c){return this.fromWireType(la[c>>3])};default:throw new TypeError(`invalid float width (${b}): ${a}`);}},La=(a,b)=>Object.defineProperty(b,"name",{value:a}),Ma=a=>{for(;a.length;){var b=
a.pop();a.pop()(b)}};function Na(a){for(var b=1;b<a.length;++b)if(null!==a[b]&&void 0===a[b].B)return!0;return!1}function Oa(a){var b=Function;if(!(b instanceof Function))throw new TypeError(`new_ called with constructor type ${typeof b} which is not a function`);var c=La(b.name||"unknownFunctionName",function(){});c.prototype=b.prototype;c=new c;a=b.apply(c,a);return a instanceof Object?a:c}
for(var Pa=(a,b)=>{if(void 0===f[a].A){var c=f[a];f[a]=function(...d){if(!f[a].A.hasOwnProperty(d.length))throw new T(`Function '${b}' called with an invalid number of arguments (${d.length}) - expects one of (${f[a].A})!`);return f[a].A[d.length].apply(this,d)};f[a].A=[];f[a].A[c.F]=c}},Qa=(a,b,c)=>{if(f.hasOwnProperty(a)){if(void 0===c||void 0!==f[a].A&&void 0!==f[a].A[c])throw new T(`Cannot register public name '${a}' twice`);Pa(a,a);if(f[a].A.hasOwnProperty(c))throw new T(`Cannot register multiple overloads of a function with the same number of arguments (${c})!`);
f[a].A[c]=b}else f[a]=b,f[a].F=c},Ra=(a,b)=>{for(var c=[],d=0;d<a;d++)c.push(J[b+4*d>>2]);return c},Sa=[],Ta,Ua=(a,b)=>{a=P(a);var c;(c=Sa[b])||(Sa[b]=c=Ta.get(b));if("function"!=typeof c)throw new T(`unknown function pointer with signature ${a}: ${b}`);return c},Va=f.UnboundTypeError=((a,b)=>{var c=La(b,function(d){this.name=b;this.message=d;d=Error(d).stack;void 0!==d&&(this.stack=this.toString()+"\n"+d.replace(/^Error(:[^\n]*)?\n/,""))});c.prototype=Object.create(a.prototype);c.prototype.constructor=
c;c.prototype.toString=function(){return void 0===this.message?this.name:`${this.name}: ${this.message}`};return c})(Error,"UnboundTypeError"),Xa=a=>{a=Wa(a);var b=P(a);X(a);return b},Ya=(a,b)=>{function c(g){e[g]||R[g]||(S[g]?S[g].forEach(c):(d.push(g),e[g]=!0))}var d=[],e={};b.forEach(c);throw new Va(`${a}: `+d.map(Xa).join([", "]));},Za=a=>{a=a.trim();const b=a.indexOf("(");return-1===b?a:a.slice(0,b)},$a=(a,b,c)=>{var d=F;if(0<c){c=b+c-1;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=
g&&57343>=g){var m=a.charCodeAt(++e);g=65536+((g&1023)<<10)|m&1023}if(127>=g){if(b>=c)break;d[b++]=g}else{if(2047>=g){if(b+1>=c)break;d[b++]=192|g>>6}else{if(65535>=g){if(b+2>=c)break;d[b++]=224|g>>12}else{if(b+3>=c)break;d[b++]=240|g>>18;d[b++]=128|g>>12&63}d[b++]=128|g>>6&63}d[b++]=128|g&63}}d[b]=0}},ab=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},bb="undefined"!=typeof TextDecoder?new TextDecoder:void 0,cb=(a=0,b=
NaN)=>{var c=F,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&bb)return bb.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var g=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|g);else{var m=c[a++]&63;e=224==(e&240)?(e&15)<<12|g<<6|m:(e&7)<<18|g<<12|m<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},db="undefined"!=typeof TextDecoder?new TextDecoder("utf-16le"):void 0,
eb=(a,b)=>{var c=a>>1;for(var d=c+b/2;!(c>=d)&&H[c];)++c;c<<=1;if(32<c-a&&db)return db.decode(F.subarray(a,c));c="";for(d=0;!(d>=b/2);++d){var e=G[a+2*d>>1];if(0==e)break;c+=String.fromCharCode(e)}return c},fb=(a,b,c)=>{c??=2147483647;if(2>c)return 0;c-=2;var d=b;c=c<2*a.length?c/2:a.length;for(var e=0;e<c;++e)G[b>>1]=a.charCodeAt(e),b+=2;G[b>>1]=0;return b-d},gb=a=>2*a.length,hb=(a,b)=>{for(var c=0,d="";!(c>=b/4);){var e=I[a+4*c>>2];if(0==e)break;++c;65536<=e?(e-=65536,d+=String.fromCharCode(55296|
e>>10,56320|e&1023)):d+=String.fromCharCode(e)}return d},ib=(a,b,c)=>{c??=2147483647;if(4>c)return 0;var d=b;c=d+c-4;for(var e=0;e<a.length;++e){var g=a.charCodeAt(e);if(55296<=g&&57343>=g){var m=a.charCodeAt(++e);g=65536+((g&1023)<<10)|m&1023}I[b>>2]=g;b+=4;if(b+4>c)break}I[b>>2]=0;return b-d},jb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);55296<=d&&57343>=d&&++c;b+=4}return b},kb=Array(256),Y=0;256>Y;++Y)kb[Y]=String.fromCharCode(Y);ya=kb;W.push(0,1,void 0,1,null,1,!0,1,!1,1);
f.count_emval_handles=()=>W.length/2-5-V.length;
var mb={c:(a,b,c)=>{var d=new va(a);J[d.D+16>>2]=0;J[d.D+4>>2]=b;J[d.D+8>>2]=c;wa=a;xa++;throw wa;},l:()=>na(""),f:(a,b,c)=>{b=P(b);U(a,{name:b,fromWireType:d=>d,toWireType:function(d,e){if("bigint"!=typeof e&&"number"!=typeof e)throw null===e?e="null":(d=typeof e,e="object"===d||"array"===d||"function"===d?e.toString():""+e),new TypeError(`Cannot convert "${e}" to ${this.name}`);"number"==typeof e&&(e=BigInt(e));return e},C:8,readValueFromPointer:Da(b,c,-1==b.indexOf("u")),B:null})},j:(a,b,c,d)=>
{b=P(b);U(a,{name:b,fromWireType:function(e){return!!e},toWireType:function(e,g){return g?c:d},C:8,readValueFromPointer:function(e){return this.fromWireType(F[e])},B:null})},h:a=>U(a,Ga),e:(a,b,c)=>{b=P(b);U(a,{name:b,fromWireType:d=>d,toWireType:(d,e)=>e,C:8,readValueFromPointer:Ha(b,c),B:null})},g:(a,b,c,d,e,g,m)=>{var h=Ra(b,c);a=P(a);a=Za(a);e=Ua(d,e);Qa(a,function(){Ya(`Cannot call ${a} due to unbound types`,h)},b-1);Ba(h,l=>{var k=[l[0],null].concat(l.slice(1));l=a;var n=a;var r=e,p=k.length;
if(2>p)throw new T("argTypes array size mismatch! Must at least get return value and 'this' types!");var D=null!==k[1]&&!1,K=Na(k),Ia="void"!==k[0].name;r=[n,za,r,g,Ma,k[0],k[1]];for(var y=0;y<p-2;++y)r.push(k[y+2]);if(!K)for(y=D?1:2;y<k.length;++y)null!==k[y].B&&r.push(k[y].B);K=Na(k);y=k.length-2;var t=[],L=["fn"];D&&L.push("thisWired");for(p=0;p<y;++p)t.push(`arg${p}`),L.push(`arg${p}Wired`);t=t.join(",");L=L.join(",");t=`return function (${t}) {\n`;K&&(t+="var destructors = [];\n");var Ja=K?"destructors":
"null",ca="humanName throwBindingError invoker fn runDestructors retType classParam".split(" ");D&&(t+=`var thisWired = classParam['toWireType'](${Ja}, this);\n`);for(p=0;p<y;++p)t+=`var arg${p}Wired = argType${p}['toWireType'](${Ja}, arg${p});\n`,ca.push(`argType${p}`);t+=(Ia||m?"var rv = ":"")+`invoker(${L});\n`;if(K)t+="runDestructors(destructors);\n";else for(p=D?1:2;p<k.length;++p)D=1===p?"thisWired":"arg"+(p-2)+"Wired",null!==k[p].B&&(t+=`${D}_dtor(${D});\n`,ca.push(`${D}_dtor`));Ia&&(t+="var ret = retType['fromWireType'](rv);\nreturn ret;\n");
let [Ka,qb]=[ca,t+"}\n"];Ka.push(qb);k=Oa(Ka)(...r);n=La(n,k);k=b-1;if(!f.hasOwnProperty(l))throw new Aa("Replacing nonexistent public symbol");void 0!==f[l].A&&void 0!==k?f[l].A[k]=n:(f[l]=n,f[l].F=k);return[]})},b:(a,b,c,d,e)=>{b=P(b);-1===e&&(e=4294967295);e=h=>h;if(0===d){var g=32-8*c;e=h=>h<<g>>>g}var m=b.includes("unsigned")?function(h,l){return l>>>0}:function(h,l){return l};U(a,{name:b,fromWireType:e,toWireType:m,C:8,readValueFromPointer:Da(b,c,0!==d),B:null})},a:(a,b,c)=>{function d(g){return new e(E.buffer,
J[g+4>>2],J[g>>2])}var e=[Int8Array,Uint8Array,Int16Array,Uint16Array,Int32Array,Uint32Array,Float32Array,Float64Array,BigInt64Array,BigUint64Array][b];c=P(c);U(a,{name:c,fromWireType:d,C:8,readValueFromPointer:d},{G:!0})},i:(a,b)=>{b=P(b);U(a,{name:b,fromWireType:function(c){for(var d=J[c>>2],e=c+4,g,m=e,h=0;h<=d;++h){var l=e+h;if(h==d||0==F[l])m=m?cb(m,l-m):"",void 0===g?g=m:(g+=String.fromCharCode(0),g+=m),m=l+1}X(c);return g},toWireType:function(c,d){d instanceof ArrayBuffer&&(d=new Uint8Array(d));
var e="string"==typeof d;if(!(e||ArrayBuffer.isView(d)&&1==d.BYTES_PER_ELEMENT))throw new T("Cannot pass non-string to std::string");var g=e?ab(d):d.length;var m=lb(4+g+1),h=m+4;J[m>>2]=g;e?$a(d,h,g+1):F.set(d,h);null!==c&&c.push(X,m);return m},C:8,readValueFromPointer:Fa,B(c){X(c)}})},d:(a,b,c)=>{c=P(c);if(2===b){var d=eb;var e=fb;var g=gb;var m=h=>H[h>>1]}else 4===b&&(d=hb,e=ib,g=jb,m=h=>J[h>>2]);U(a,{name:c,fromWireType:h=>{for(var l=J[h>>2],k,n=h+4,r=0;r<=l;++r){var p=h+4+r*b;if(r==l||0==m(p))n=
d(n,p-n),void 0===k?k=n:(k+=String.fromCharCode(0),k+=n),n=p+b}X(h);return k},toWireType:(h,l)=>{if("string"!=typeof l)throw new T(`Cannot pass non-string to C++ string type ${c}`);var k=g(l),n=lb(4+k+b);J[n>>2]=k/b;e(l,n+4,k+b);null!==h&&h.push(X,n);return n},C:8,readValueFromPointer:Fa,B(h){X(h)}})},k:(a,b)=>{b=P(b);U(a,{H:!0,name:b,C:0,fromWireType:()=>{},toWireType:()=>{}})},m:a=>{var b=F.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);
a:{d=(Math.min(2147483648,65536*Math.ceil(Math.max(a,d)/65536))-C.buffer.byteLength+65535)/65536|0;try{C.grow(d);ma();var e=1;break a}catch(g){}e=void 0}if(e)return!0}return!1}},Z;
(async function(){function a(d){Z=d.exports;C=Z.n;ma();Ta=Z.q;M--;f.monitorRunDependencies?.(M);0==M&&N&&(d=N,N=null,d());return Z}M++;f.monitorRunDependencies?.(M);var b={a:mb};if(f.instantiateWasm)return new Promise(d=>{f.instantiateWasm(b,(e,g)=>{a(e,g);d(e.exports)})});O??=f.locateFile?f.locateFile("libdebversion.wasm",v):v+"libdebversion.wasm";try{var c=await qa(b);return a(c.instance)}catch(d){return q(d),Promise.reject(d)}})();
var Wa=a=>(Wa=Z.p)(a),lb=a=>(lb=Z.r)(a),X=a=>(X=Z.s)(a),nb=a=>(nb=Z.t)(a),ob=a=>(ob=Z.u)(a),pb=()=>(pb=Z.v)();f.ccall=(a,b,c,d)=>{var e={string:k=>{var n=0;if(null!==k&&void 0!==k&&0!==k){n=ab(k)+1;var r=ob(n);$a(k,r,n);n=r}return n},array:k=>{var n=ob(k.length);E.set(k,n);return n}};a=f["_"+a];var g=[],m=0;if(d)for(var h=0;h<d.length;h++){var l=e[c[h]];l?(0===m&&(m=pb()),g[h]=l(d[h])):g[h]=d[h]}c=a(...g);return c=function(k){0!==m&&nb(m);return"string"===b?k?cb(k):"":"boolean"===b?!!k:k}(c)};
function rb(){function a(){f.calledRun=!0;if(!ha){Z.o();aa(f);f.onRuntimeInitialized?.();if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var b=f.postRun.shift();sa.unshift(b)}ra(sa)}}if(0<M)N=rb;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)ua();ra(ta);0<M?N=rb:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);a()},1)):a()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.pop()();rb();moduleRtn=ba;


  return moduleRtn;
}
);
})();
if (typeof exports === 'object' && typeof module === 'object') {
  module.exports = Module;
  // This default export looks redundant, but it allows TS to import this
  // commonjs style module.
  module.exports.default = Module;
} else if (typeof define === 'function' && define['amd'])
  define([], () => Module);
